### ISSUE TITLE
Players with expired timers can allow other players to bypass cooldowns on a vault

### ISSUE THREAD

**Issue by lerokko** [DTanJP/Spigot-ForgetfulTrialVault#1]
Player reporting an issue where when their timer has expired and they click on a vault to reset it (but not loot it yet), it is reset for all players including those who should still have to wait.

As far as I understand it from the plugin description the vault should only reset for the player whose cooldown/timer has passed. They should not be able to reset the timers of other.

**Comment by DTanJP** [comment]
Hello Lerokko,

Which version of the plugin are you using? My initial release has this issue.
That version is the only one that replaces the vault block and reverts it back, therefore wiping everyone's data on who has looted that block.

I released a updated version (v1.0.1) which has the timers and only modifies the server NBT data instead of wiping everyone's data.

**Comment by DTanJP** [comment]
No response for 3 days. Closing this issue.

**Comment by lerokko** [comment]
Sorry for not responding. I was busy. As for now I am unable to reproduce this issue it was reported by one of my moderators. You can keep this issue closed. I would reopen this if I ever be able to reproduce it.
